version: "3.8"

services:
  tssk:
    image: netplexflix/tssk:latest
    container_name: tssk
    environment:
      - CRON=0 2 * * * # every day at 2am
      - DOCKER=true # important for path reference
      - TZ=Europe/Amsterdam # Set your timezone
    volumes:
      - ./config:/app/config
      - ./kometa:/config/kometa
    restart: unless-stopped
