################################################################################
##########                         GENERAL:                           ##########
################################################################################
debug: false

sonarr_url: 'http://localhost:8989'
sonarr_api_key: 'YOUR_SONARR_API_KEY'
sonarr_timeout: 90
use_tvdb: false

skip_unmonitored: true
ignore_finales_tags: ignorefinales
utc_offset: +0
simplify_next_week_dates: true

process_new_shows: true
process_new_season_soon: true
process_new_season_started: true
process_upcoming_episode: true
process_upcoming_finale: true
process_season_finale: true
process_final_episode: true
process_returning_shows: true
process_ended_shows: true
process_canceled_shows: true

################################################################################
##########                         NEW SHOW:                          ##########
################################################################################

recent_days_new_show: 7

collection_new_show:
  collection_name: "New Show"
  item_label: NewShow
  non_item_remove_label: NewShow
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_new_show:
  enable: true
  back_color: "#EB3233"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 50

text_new_show:
  use_text: "RECENTLY ADDED"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 50

################################################################################
##########                     NEW SEASON SOON:                       ##########
################################################################################

future_days_new_season: 31

collection_new_season:
  collection_name: "New Season Soon"
  item_label: NewSeasonSoon
  non_item_remove_label: NewSeasonSoon
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_new_season:
  enable: true
  back_color: "#228B22"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 25

text_new_season:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NEW SEASON"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 25

################################################################################
##########                    NEW SEASON STARTED:                     ##########
################################################################################

recent_days_new_season_started: 7

collection_new_season_started:
  collection_name: "New Season Started"
  item_label: NewSeasonStarted
  non_item_remove_label: NewSeasonStarted
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_new_season_started:
  enable: true
  back_color: "#228B22"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 35

text_new_season_started:
  use_text: "SEASON [#] STARTED"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 35
  
################################################################################
##########                     UPCOMING EPISODE:                      ##########
################################################################################

future_days_upcoming_episode: 31

collection_upcoming_episode:
  collection_name: "Upcoming Episode"
  item_label: UpcomingEpisode
  non_item_remove_label: UpcomingEpisode
  build_collection: false
  ignore_blank_results: true
  sync_mode: append
  
backdrop_upcoming_episode:
  enable: true
  back_color: "#006580"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 20

text_upcoming_episode:
  date_format: "ddd dd/mm"
  capitalize_dates: true
  use_text: "NEXT EPISODE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 20
  
################################################################################
##########                      UPCOMING FINALE:                      ##########
################################################################################

future_days_upcoming_finale: 31

collection_upcoming_finale:
  collection_name: "Upcoming Finale"
  item_label: UpcomingFinale
  non_item_remove_label: UpcomingFinale
  build_collection: false
  ignore_blank_results: true
  sync_mode: append
  
backdrop_upcoming_finale:
  enable: true
  back_color: "#9932CC"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 40

text_upcoming_finale:
  date_format: "ddd dd/mm"      # e.g., "yyyy-mm-dd", "mm/dd", "dd/mm", etc.
  capitalize_dates: true
  use_text: "FINALE AIRS"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 40

################################################################################
##########                     SEASON FINALE OUT:                     ##########
################################################################################

recent_days_season_finale: 7

collection_season_finale:
  collection_name: "Season Finale"
  item_label: SeasonFinale
  non_item_remove_label: SeasonFinale
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_season_finale:
  enable: true
  back_color: "#ffb902"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 30

text_season_finale:
  use_text: "SEASON FINALE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#000000"
  group: TSSK_text
  weight: 30

################################################################################
##########                     FINAL EPISODE OUT:                     ##########
################################################################################

recent_days_final_episode: 7

collection_final_episode:
  collection_name: "Final Episode"
  item_label: FinalEpisode
  non_item_remove_label: FinalEpisode
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_final_episode:
  enable: true
  back_color: "#ffb902"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 30

text_final_episode:
  use_text: "FINAL EPISODE"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#000000"
  group: TSSK_text
  weight: 30

################################################################################
##########                         RETURNING:                         ##########
################################################################################

collection_returning:
  collection_name: "Returning Shows"
  item_label: ReturningShows
  non_item_remove_label: ReturningShows
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_returning:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 10

text_returning:
  use_text: "R E T U R N I N G"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#ff9000"
  group: TSSK_text
  weight: 10

################################################################################
##########                           ENDED:                           ##########
################################################################################

collection_ended:
  collection_name: "Ended Shows"
  item_label: EndedShows
  non_item_remove_label: EndedShows
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_ended:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 10

text_ended:
  use_text: "E N D E D"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#00ff3d"
  group: TSSK_text
  weight: 10

################################################################################
##########                         CANCELED:                          ##########
################################################################################

collection_canceled:
  collection_name: "Canceled Shows"
  item_label: CanceledShows
  non_item_remove_label: CanceledShows
  build_collection: false
  ignore_blank_results: true
  sync_mode: append

backdrop_canceled:
  enable: false
  back_color: "#000000"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 10

text_canceled:
  use_text: "C A N C E L E D"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 50
  font_size: 70
  font_color: "#EB3233"
  group: TSSK_text
  weight: 10